name: ItemTell
main: NoobMCBG\ItemTell\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: NoobMCBG

commands: 
 giveitemtell:
    description: "Command give tell item for players"
    aliases: [giveitem, git]
    usage: "/giveitemtell <player>"
    
permission:
  itemtell.command.give:
     description: Permission use command /giveitemtell
     default: op
