---
# Config.yml
# ItemTell Plugin
# github: https//github.com/NoobMCBG

# Join to give item
# Please fill "true" or "false" with "true" to make them work, "false" not to make them work
joinItem: "true"

# Name Item use to Tell
item-name: "§aItemTell"

# Lore Item use to Tell
item-lore: "§5Right-Click to use"

# No Permission use command /giveitemtell
no-permission: "§cYou no permission to use command"

# ID META AMOUNT
item-id: 328
item-meta: 0
item-amount: 1
...